// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7-Zlg9y0lFQLhJpCDH7EJKCMNqXezrXM',
    appId: '1:494688131908:web:28654303a615a9e0cad511',
    messagingSenderId: '494688131908',
    projectId: 'ai-crypto-chat',
    authDomain: 'ai-crypto-chat.firebaseapp.com',
    storageBucket: 'ai-crypto-chat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQeY8Uw6Sw53qS-L9oMdZHBSSaA6gw3lE',
    appId: '1:494688131908:android:d27b1e955c7c7da5cad511',
    messagingSenderId: '494688131908',
    projectId: 'ai-crypto-chat',
    storageBucket: 'ai-crypto-chat.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrukR2J1BqqIeQQ14fuGDVIKu_pmNuuEI',
    appId: '1:494688131908:ios:017a3f91c4a6568fcad511',
    messagingSenderId: '494688131908',
    projectId: 'ai-crypto-chat',
    storageBucket: 'ai-crypto-chat.firebasestorage.app',
    androidClientId: '494688131908-rppuofcg4cakl99in2pmrq1ivt1dm83j.apps.googleusercontent.com',
    iosClientId: '494688131908-p7ssk8bp9f3oe1rip150aqvpogq8pgn8.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiCryptoChat',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrukR2J1BqqIeQQ14fuGDVIKu_pmNuuEI',
    appId: '1:494688131908:ios:017a3f91c4a6568fcad511',
    messagingSenderId: '494688131908',
    projectId: 'ai-crypto-chat',
    storageBucket: 'ai-crypto-chat.firebasestorage.app',
    androidClientId: '494688131908-rppuofcg4cakl99in2pmrq1ivt1dm83j.apps.googleusercontent.com',
    iosClientId: '494688131908-p7ssk8bp9f3oe1rip150aqvpogq8pgn8.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiCryptoChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7-Zlg9y0lFQLhJpCDH7EJKCMNqXezrXM',
    appId: '1:494688131908:web:cdd919f6e2f6c3ebcad511',
    messagingSenderId: '494688131908',
    projectId: 'ai-crypto-chat',
    authDomain: 'ai-crypto-chat.firebaseapp.com',
    storageBucket: 'ai-crypto-chat.firebasestorage.app',
  );
}
